name: Build Console App

on:
  push:
    branches: [ main ]

jobs:
  # A job that builds a .NET Core console application using Telerik Document Processing Libraries 
  # It uses a Windows runner and builds for Any CPU
  build_console:
    runs-on: windows-latest
    
    env:
      TELERIK_USERNAME: ${{ secrets.MyTelerikAccountUsername }}
      TELERIK_PASSWORD: ${{ secrets.MyTelerikAccountPassword }}
      SolutionPath: DevOpsExamples/src/Console/Console.sln
      NuGetConfigPath: DevOpsExamples/src/Console/NuGet.Config
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1.6.0
        with:
          dotnet-version: 3.1.302
      
      - name: Restore NuGet Packages
        run: dotnet restore $env:SolutionPath --configfile $env:NuGetConfigPath --runtime any

      - name: Build Solution
        run: dotnet build $env:SolutionPath --configfile $env:NuGetConfigPath --configuration Release --runtime any  
