name: Build Console App

on:
  push:
    branches: [ main ]

jobs:
  # A job that builds a .NET Core console application using Telerik Document Processing Libraries 
  # It uses a Windows runner and builds for Any CPU
  build_console:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1.7.2
      with:
        dotnet-version: 3.1.302
    
    - name: Restore NuGet Packages
      run: dotnet restore src\Console\Console.sln --configfile src\Console\NuGet.Config --runtime win-x86
      env:
        TELERIK_USERNAME: ${{ secrets.MyTelerikAccountUsername }}
        TELERIK_PASSWORD: ${{ secrets.MyTelerikAccountPassword }}

    - name: Build Solution
      run: dotnet build src\Console\Console.sln --configfile src\Console\NuGet.Config --configuration Release --runtime win-x86
      env:
        TELERIK_USERNAME: ${{ secrets.MyTelerikAccountUsername }}
        TELERIK_PASSWORD: ${{ secrets.MyTelerikAccountPassword }}