name: Build MAUI Project

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**/*.md'
      - '**/*.gitignore'
      - '**/*.gitattributes'

jobs:
# ********************** WinUI3 MAUI app | Windows build ************************* #
  maui-on-windows:
    runs-on: windows-latest
    env:
      ProjectPath: src/MAUI/HelloMaui/HelloMaui.csproj
      SolutionPath: src/MAUI/DemoApp.sln
      NuGetConfigPath: src/MAUI/NuGet.Config
      BuildConfig: Debug
      IsRunningOnCI: true
      DotNetVersion: 6.0.100-preview.6.21355.2
      DotNet.Cli.Telemetry.OptOut: true
      MauiCheckVersion: 0.6.1
      MauiCheckManifest: https://raw.githubusercontent.com/Redth/dotnet-maui-check/main/manifests/maui-dev.manifest.json
      Actions_Allow_Unsecure_Commands: true # Allows env variables on the job-level
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Generate version number
      shell: pwsh
      run: |
        $buildDay = Get-Date -Format "yyyy.Mdd"
        $ver = $buildDay + "." + $env:GITHUB_RUN_NUMBER + ".0"
        echo "APP_VERSION=$ver" >> $GITHUB_ENV

    - name: Install .NET 6 SDK
      shell: pwsh
      run: |
        $ProgressPreference = 'SilentlyContinue'
        Invoke-WebRequest -Uri "https://dot.net/v1/dotnet-install.ps1" -OutFile dotnet-install.ps1
        & .\dotnet-install.ps1 -Version $env:DotNetVersion -InstallDir "$env:ProgramFiles\dotnet\" -Verbose
        & dotnet --list-sdks

    - name: Run maui check
      shell: pwsh
      run: |
        & dotnet tool update --global redth.net.maui.check --version $env:MauiCheckVersion --add-source https://api.nuget.org/v3/index.json
        & maui-check --ci --non-interactive --fix --skip androidsdk --skip xcode --skip vswin --skip vsmac --manifest $env:MauiCheckManifest

    - name: Restore NuGet packages
      shell: pwsh
      run: |
        dotnet restore $env:ProjectPath --configfile $env:NuGetConfigPath
      env:
        TELERIK_USERNAME: ${{ secrets.MyTelerikAccountUsername }}
        TELERIK_PASSWORD: ${{ secrets.MyTelerikAccountPassword }}  

    - name: Build Maui project
      shell: pwsh
      run: dotnet build $env:SolutionPath -c $env:BuildConfig --no-restore
    
    - name: Upload build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: maui-windows-artifacts
        path: '*Android\**\*-Signed.apk'

# ********************** NET 6 MAUI app | MacOS Build ************************* #

  maui-on-mac:
    #runs-on: macos-latest
    # in order to easily use Xcode 13 beta, I run tthis job on alocal Mac using a runner.
    runs-on: self-hosted
    env:
      ProjectPath: src/MAUI/HelloMaui/HelloMaui.csproj
      SolutionPath: src/MAUI/DemoApp.sln
      NuGetConfigPath: src/MAUI/NuGet.Config
      IsRunningOnCI: true
      DotNetVersion: 6.0.100-preview.6.21355.2
      DotNet.Cli.Telemetry.OptOut: true
      MauiCheckVersion: 0.6.1
      MauiCheckManifest: https://raw.githubusercontent.com/Redth/dotnet-maui-check/main/manifests/maui-dev.manifest.json
      Actions_Allow_Unsecure_Commands: true # Allows env variables on the job-level

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    
    - name: Generate version number
      shell: bash
      run: |
        buildDay=`date +%Y.%m%d`
        echo $buildDay
        runNum=${{ github.run_number }}
        ver="${buildDay}.${runNum}.0"
        echo $ver
        echo "APP_VERSION=$ver" >> $GITHUB_ENV

    - name: Setup dotnet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'

# Not needed when running on a self-hosted machine with the tools preinstalled
    # - name: Install .NET 6 SDK and  check
    #   shell: bash
    #   run: |
    #     # echo "$env:DotNetRoot" >> $GITHUB_PATH
    #     # echo "$env:DotNetTools" >> $GITHUB_PATH
    #     curl -L https://raw.githubusercontent.com/dotnet/install-scripts/7a9d5dcab92cf131fc2d8977052f8c2c2d540e22/src/dotnet-install.sh > dotnet-install.sh
    #     sh dotnet-install.sh --version $env:DotNetVersion --install-dir '/usr/local/share/dotnet/' --verbose
    #     dotnet --list-sdks

    # - name: maui-check
    #   shell: bash
    #   run: |
    #     dotnet tool update --global redth.net.maui.check --version $env:MauiCheckVersion --add-source https://api.nuget.org/v3/index.json
    #     maui-check --ci --non-interactive --fix --skip androidsdk --skip xcode --skip vswin --skip vsmac --manifest $env:MauiCheckManifest

    # - name: select Xcode 13
    #   shell: bash
    #   run: sudo xcode-select -s /Applications/Xcode_13.app

    # - name: configure vsmac xcode
    #   shell: bash
    #   run: |
    #     set -x
    #     mkdir -p ~/Library/Preferences/Xamarin
    #     rm -f ~/Library/Preferences/Xamarin/Settings.plist
    #     /usr/libexec/PlistBuddy -c "add :AppleSdkRoot string $(dirname $(dirname $(xcode-select -p)))" ~/Library/Preferences/Xamarin/Settings.plist || true
    #     cat ~/Library/Preferences/Xamarin/Settings.plist || true

    - name: Restore NuGet packages
      shell: bash
      run: |
        dotnet restore $env:ProjectPath --configfile $env:NuGetConfigPath
      env:
        TELERIK_USERNAME: ${{ secrets.MyTelerikAccountUsername }}
        TELERIK_PASSWORD: ${{ secrets.MyTelerikAccountPassword }}
    
    - name: Build Solution
      shell: bash
      run: dotnet build $env:SolutionPath -c Debug -t net6.0-ios --no-restore
    
    - name: Upload build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: maui-mac-artifacts
        path: '*iOS/**/*.app/**'
