name: Build WPF Application

on:
  push:
    branches: [ main ]

jobs:
  # A job that builds a .NET Core WPF application using Telerik UI for WPF
  # It uses a Windows runner and builds for x86 and x64 runtime
  build_desktop:
    runs-on: windows-latest # WPF apps must be built on Windows runners
    
    env:
      TELERIK_USERNAME: ${{ secrets.MyTelerikAccountUsername }}
      TELERIK_PASSWORD: ${{ secrets.MyTelerikAccountPassword }}
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1.6.0
        with:
          dotnet-version: 3.1.302
      
      - name: Setup MSBuild.exe
        uses: microsoft/setup-msbuild@v1.0.1
      
      - name: NuGet Restore
        run: dotnet restore 'D:\a\DevOpsExamples\src\Wpf\MyWpfApp\MyWpfApp.csproj' --configfile 'D:\a\DevOpsExamples\src\nuget.config' --runtime win-x86

      - name: Build the Wpf application (populate the obj folder)
        run: msbuild 'D:\a\DevOpsExamples\src\Wpf\MyWpfApp\MyWpfApp.csproj' /t:Restore /p:Configuration=Release /p:RuntimeIdentifier=win-x86
