name: Build Angular Application

on:
  push:
    branches: [ main ]

jobs:
  build_angular:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Install NPM modules
      working-directory: src/Kendo/angular-demo
      run: npm install
    
    # The value of KENDO_LICENSE_KEY is stored as a GitHub repo secret (Settings -> Secrets -> Actions)
    # Get your key here https://www.telerik.com/kendo-angular-ui/components/my-license/#toc-download-your-license-key
    - name: Activate Kendo UI License
      working-directory: src/Kendo/angular-demo
      run: npx kendo-ui-license activate
      env:
        KENDO_UI_LICENSE: ${{ secrets.KENDO_LICENSE_KEY }}

    - name: Build
      working-directory: src/Kendo/angular-demo
      run: npm run build --prod
      
    - name: Build And Deploy to Azure Static Web Apps
      uses: Azure/static-web-apps-deploy@v1
      with:
        azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_DELIGHTFUL_GROUND_0D7A89D0F }}
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        action: "upload"
        app_location: "/src/Kendo/angular-demo"
        api_location: "" 
        output_location: "dist" 
