name: Build Console App

on:
  push:
    branches: [ main ]

jobs:
  # A job that builds a .NET Core console application using Telerik Document Processing Libraries 
  # It uses a Mac OS runner and builds for Any CPU
  build_console:
    runs-on: macos-latest
    
    env:
      TELERIK_USERNAME: ${{ secrets.MyTelerikAccountUsername }}
      TELERIK_PASSWORD: ${{ secrets.MyTelerikAccountPassword }}
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1.6.0
        with:
          dotnet-version: 3.1.302
      
      - name: Restore NuGet Packages
        run: dotnet restore D:\a\DevOpsExamples\src\Console\Console.sln --configfile D:\a\DevOpsExamples\src\Console\NuGet.Config --runtime any

      - name: Build Solution
        run: dotnet build D:\a\DevOpsExamples\src\Console\Console.sln --configuration Release --configfile D:\a\DevOpsExamples\src\Console\NuGet.Config --runtime any  
